spring:
  application:
    name: animalworld
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: supersecret
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
