spring:
  application:
    name: animalworld
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/database}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:supersecret}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
